name: 'pt4_dbt'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pt4_dbt:
    +database: PT4_DBT
    silver:
      +materialized: view
      +schema: silver   # Recomendado para que se guarde en el esquema SILVER
    gold:
      +materialized: table
      +schema: gold     # Recomendado para que se guarde en el esquema GOLD

seeds:
  pt4_dbt:
    +database: PT4_DBT
    +schema: seeds
    +quote_columns: false

snapshots:
  pt4_dbt:
    +database: PT4_DBT
    +target_schema: snapshots